cmake_minimum_required(VERSION 3.18)
project(uipreview LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
find_package(Qt6 REQUIRED COMPONENTS Widgets UiTools)
add_executable(uipreview main.cpp ../../src/utils/MacLayoutStyle.cpp)
target_include_directories(uipreview PRIVATE ../../src/utils)
set_target_properties(uipreview PROPERTIES AUTOMOC ON)
target_link_libraries(uipreview PRIVATE Qt6::Widgets Qt6::UiTools)
