# Biscuit: partner API keys for official builds.
#
# The key comes from secrets.cmake (ignored by git) and is written, XOR-masked
# with a random pad, to a header in the build tree. It never appears in the
# repository, in compiler flags or in plain text in the binary. This only slows
# down extraction: a key shipped in an app can never be fully hidden.
#
# biscuit_write_secret_header(<name> <value> <output file>)
function(biscuit_write_secret_header name value output)
    string(LENGTH "${value}" len)
    string(HEX "${value}" hex)
    math(EXPR hexlen "${len} * 2")
    string(RANDOM LENGTH ${hexlen} ALPHABET "0123456789abcdef" pad)
    set(masked "")
    set(padbytes "")
    math(EXPR last "${len} - 1")
    foreach(i RANGE ${last})
        math(EXPR o "${i} * 2")
        string(SUBSTRING "${hex}" ${o} 2 kb)
        string(SUBSTRING "${pad}" ${o} 2 pb)
        math(EXPR x "0x${kb} ^ 0x${pb}" OUTPUT_FORMAT HEXADECIMAL)
        list(APPEND masked "${x}")
        list(APPEND padbytes "0x${pb}")
    endforeach()
    list(JOIN masked ", " masked)
    list(JOIN padbytes ", " padbytes)
    file(WRITE "${output}" "// Generated by cmake/BiscuitSecrets.cmake. Do not commit.\n#pragma once\n"
         "// volatile: keeps the compiler from folding the XOR back into the plain key.\n"
         "static volatile const unsigned char ${name}_masked[] = {${masked}};\n"
         "static volatile const unsigned char ${name}_pad[] = {${padbytes}};\n"
         "static constexpr unsigned long ${name}_len = ${len};\n")
endfunction()
