name: ci/gh-actions/build

on: [push, pull_request]

jobs:
  build-ubuntu:
    name: "Ubuntu 24.04 (build + tests)"
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04
    steps:
      - name: update apt
        run: apt update
      - name: install dependencies
        run: apt -y install git cmake build-essential ccache libssl-dev libunbound-dev libboost-all-dev
                            libqrencode-dev qt6-base-dev qt6-svg-dev qt6-websockets-dev qt6-multimedia-dev
                            qt6-wayland-dev libzip-dev libsodium-dev libgcrypt20-dev libx11-xcb-dev
                            protobuf-compiler libprotobuf-dev libhidapi-dev libzxing-dev libusb-dev
                            libusb-1.0-0-dev
      - name: configure git
        run: git config --global --add safe.directory '*'
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: build
        run: |
          cmake -S . -B build -DWITH_SCANNER=OFF -DBUILD_TESTS=ON
          cmake --build build -j $(nproc)
      - name: unit tests
        run: ctest --test-dir build/tests --output-on-failure
